version: "3"

services:
  logs-mongo-express:
    image: mongo-express:0.49.0
    environment:
      - ME_CONFIG_MONGODB_SERVER=logs-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    ports:
      - "8081:8081"
    links:
      - logs-mongo
  logs-mongo:
    image: mongo:4.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
